# Generated by Django 4.2.18 on 2025-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
