# Generated by Django 4.2.18 on 2025-02-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='modified_at',
        ),
    ]
