# Generated by Django 4.2.18 on 2025-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_text_chunks_session_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
